feat(show): check for awk dependency

diff --git a/git-activity b/git-activity
--- a/git-activity
+++ b/git-activity
@@ -106,6 +106,11 @@ __git_activity_show() {
   local -A filters
   local -i has_filters
 
+  if ! $'command' -v awk &>/dev/null; then
+    'builtin' 'printf' "Requires \`awk\`. Installation method varies by OS.\\nAborting.\\n"
+    return
+  fi
+
   date_format="+%Y-%m-%d"
 
   has_filters=$#
